doctrine:
  orm:
    mappings:
      AccountBundle:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src/AccountBundle/Domain/Model'
        prefix: 'App\AccountBundle\Domain\Model'
        alias: AccountBundle